# Generated by Django 2.1.4 on 2018-12-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termposting',
            old_name='docIDs',
            new_name='docID',
        ),
    ]
